Bintray
riboseinc/homebrew-rnp pull request #13
Opened 2019-12-05 13:04 UTC by rrrooommmaaa

Build bottle and upload to Bintray

2019-12-05 13:19 UTC, ronaldtse commented
@rrrooommmaaa can we also move this from Travis to GHA? Thanks!

2019-12-05 13:24 UTC, rrrooommmaaa commented
@ronaldtse So you want this merged (with corrections) and run on GHA "macos-latest", correct?

2019-12-05 14:41 UTC, ronaldtse commented
> So you want this merged (with corrections) and run on GHA "macos-latest", correct?

Yes please!

2019-12-05 17:25 UTC, ronaldtse requested changes

2019-12-05 17:25 UTC, ronaldtse commented on .travis.yml
> +    - TAP_NAME=riboseinc/rnp
Change to rnpgp/rnp

2019-12-05 17:25 UTC, ronaldtse commented on .travis.yml
> +    - BINTRAY_SUBJECT=skalee
Username is `rnp-ci`.

2019-12-05 17:25 UTC, ronaldtse commented on .travis.yml
> +deploy:
User is `rnp-ci`. Token can be accessed via GitHub Actions `{{ secret.BINTRAY_CI_TOKEN }}`.

2019-12-05 17:30 UTC, ronaldtse commented
FYI here's a good explanation on how brew bottles work... https://jonathanchang.org/blog/maintain-your-own-homebrew-repository-with-binary-bottles/

2019-12-08 11:41 UTC, ronaldtse requested changes

2019-12-08 11:41 UTC, ronaldtse commented on .github/workflows/publish.yml
> +        BINTRAY_API_KEY: {{ secret.BINTRAY_CI_TOKEN }}
Should be `{{ secrets.BINTRAY_CI_TOKEN }}` `secret(s)`.

2019-12-10 03:23 UTC, ronaldtse requested changes

2019-12-10 03:23 UTC, ronaldtse commented on ci/pushToBintray.sh
> +    echo "The package ${BINTRAY_PACKAGE} does not exit. It will be created"
For bash functions, the `echo` should really write to STDERR because STDOUT becomes the return value:
e.g.
```
echowarn() { echo "warning: $@" 1>&2; }
echowarn "blah";
```

2019-12-18 10:51 UTC, ronaldtse commented
@rrrooommmaaa I'm noticed in the latest commit `BINTRAY_REPO` was changed to `rnp-ci`, but I'm pretty sure it's just `rnp`...

2019-12-18 10:53 UTC, rrrooommmaaa commented
@ronaldtse That's strange, because when I go to https://bintray.com/rnp-ci I see something
and when I go to  https://bintray.com/rnp it responds with 404 error

2019-12-18 11:34 UTC, ronaldtse commented
Because:
- user is “rnp-ci”
- organization is “rnp”
- repo is “rnp”

2019-12-18 12:40 UTC, ronaldtse commented
@rrrooommmaaa the actual path is:
https://bintray.com/rnpgp/rnp

2019-12-18 12:40 UTC, ronaldtse commented
And the actual package is: https://bintray.com/rnpgp/rnp/rnp

2019-12-19 19:51 UTC, rrrooommmaaa commented
@ronaldtse I see, the problem was that the template script assumed that user performing the upload is the repo owner (subject). So I modified it to user `rnpgp` as subject and `rnp-ci` as user.
It did upload  `rnp--0.12.0.catalina.bottle.tar.gz` to `rnp` package version 0.12.0 now.

2019-12-19 23:37 UTC, ronaldtse approved these changes
This is exciting. Thank you!!

2019-12-19 23:38 UTC, ronaldtse commented
@rrrooommmaaa does this script only build on tags of the rnp repo? If so, please merge directly. Thanks.

2019-12-20 09:46 UTC, rrrooommmaaa commented
@ronaldtse The formula takes the fixed source archive: `https://github.com/rnpgp/rnp/archive/v0.12.0.tar.gz`
How would you like to update the formula? To search the latest tag like we did for snap?

2019-12-20 10:05 UTC, ronaldtse commented
> How would you like to update the formula? To search the latest tag like we did for snap?

@rrrooommmaaa yes please, that would certainly work better by reducing future work in maintaining the packages.

2019-12-20 10:07 UTC, ronaldtse commented
@rrrooommmaaa let's merge this first and have the rest in a new ticket.

2019-12-20 10:07 UTC, merged